server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: postgres://wagxstjybjxznz:c4bf6affbab906aba2bd3c0fb91410adb951e9e0e9482b6c0ba481f7a8edb30f@ec2-3-222-11-129.compute-1.amazonaws.com:5432/d5ufhr15r73toq
      username: wagxstjybjxznz
      password: c4bf6affbab906aba2bd3c0fb91410adb951e9e0e9482b6c0ba481f7a8edb30f
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none

application:
        description: Projeto criado para o Bootcamp DIO - Santander / Back-end

